### ISSUE TITLE
All games are not getting thought Handlebar

### ISSUE THREAD

**Issue by KorolyovaLara** [KorolyovaLara/TeamProject-2#21]
Can anyone spot what am I am missing?
All games get fetched, but not rendered using the handlebar.

![Screen Shot 2021-06-08 at 11 04 10 am](https://user-images.githubusercontent.com/78417151/121106527-84233600-c849-11eb-9cf1-e6b3de926e87.png)
![Screen Shot 2021-06-08 at 11 02 46 am](https://user-images.githubusercontent.com/78417151/121106534-88e7ea00-c849-11eb-9be3-a5b27ad63923.png)
![Screen Shot 2021-06-08 at 11 02 06 am](https://user-images.githubusercontent.com/78417151/121106535-89808080-c849-11eb-8274-595bf77ad1a8.png)

**Comment by tinku-bansal** [comment]
![Screenshot (288)](https://user-images.githubusercontent.com/26123970/121125645-3b2fa980-c86a-11eb-9672-20c8e2b72248.png)
I am able to fetch all the games using the same code. I think restarting the server should fix that!

**Comment by KorolyovaLara** [comment]
> I am able to fetch all the games using the same code. I think restarting the server should fix that!

Thank you @tinkubansal95  for checking/testing it for me

**Comment by KorolyovaLara** [comment]
Sorted
