### ISSUE TITLE
Navbar burger not working

### ISSUE THREAD

**Issue by seanmckay94** [KorolyovaLara/TeamProject-2#32]
Error with the Bulma navbar burger, tried some of the fixes that has worked for others with no result as of yet

**Comment by KorolyovaLara** [comment]
Hey All,
I fixed it!!! 👍🏻 

we needed a javascript to make it work and a script at the bottom of the navbar.handlebar

> $(document).ready(function () {
>   // Check for click events on the navbar burger icon
>   $(".navbar-burger").click(function () {
>     // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
>     $(".navbar-burger").toggleClass("is-active");
>     $(".navbar-menu").toggleClass("is-active");
>   });
> });
>
